name: RPG_System
version: 0.0.1
author: Hypex
main: RPG_System.Main
api-version: 1.13
commands:
   rpg:
      description: All command to control plugin
   lvl:
      description: lvl information
permissions:
   rpg.*:
      description: Gives access to all commands
   rpg.admin:
      description: Give access to admin commands
   rpg.user:
      description: Give access to user commands
depend: [Vault, PlaceholderAPI]