name: RPG_System
version: 0.0.1
author: Hypex
main: plugin.RPGSystem
api-version: 1.13
commands:
   rpg:
      description: All command to control plugin
   lvl:
      description: Lvl information
   test:
      description: Only for testing methods
permissions:
   rpg.*:
      description: Gives access to all commands
   rpg.admin:
      description: Give access to admin commands
   rpg.user:
      description: Give access to user commands
depend: [Vault, PlaceholderAPI]